#!/usr/bin/env node
/**
 * create-store — scaffold a brand-new store and register it.
 *
 *   npm run create-store "<Store Name>"
 *
 * It will: 1) generate a ready-to-use store config in /clients,
 *          2) register it with the system, and
 *          3) make it the active store.
 * No code editing required — open http://localhost:3000 after `npm run dev`.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const ROOT = process.cwd();
const CLIENTS_DIR = path.join(ROOT, "clients");
const REGISTRY = path.join(ROOT, "config", "active-client.ts");
const ENV_FILE = path.join(ROOT, ".env.local");

/* ── helpers (pure) ───────────────────────────────────────────────────────── */

export function slugify(name) {
  return String(name)
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

/** camelCase variable name from a slug, e.g. "acme-store" → "acmeStore". */
export function toVarName(slug) {
  const camel = slug.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  return /^[a-z]/.test(camel) ? camel : `store${camel.charAt(0).toUpperCase()}${camel.slice(1)}`;
}

/** Insert a line immediately before a marker comment, preserving indentation. */
export function insertBeforeMarker(source, marker, line) {
  const idx = source.indexOf(marker);
  if (idx === -1) throw new Error(`Marker not found: ${marker}`);
  const lineStart = source.lastIndexOf("\n", idx) + 1;
  const indent = source.slice(lineStart, idx);
  return source.slice(0, lineStart) + `${indent}${line}\n` + source.slice(lineStart);
}

/** Read .env.local into a key→value map (missing file → empty). */
async function readEnv() {
  try {
    const raw = await fs.readFile(ENV_FILE, "utf8");
    const out = {};
    for (const ln of raw.split(/\r?\n/)) {
      const m = ln.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m) out[m[1]] = m[2];
    }
    return out;
  } catch {
    return {};
  }
}

async function writeEnv(map) {
  const body =
    "# Generated by the ecommerce factory CLI. Safe to edit.\n" +
    Object.entries(map)
      .map(([k, v]) => `${k}=${v}`)
      .join("\n") +
    "\n";
  await fs.writeFile(ENV_FILE, body, "utf8");
}

/** Make `key` the active store, in the given mode ("production" | "demo"). */
export async function setActiveStore(key, mode = "production") {
  const env = await readEnv();
  env.PRODUCT_MODE = mode;
  env.ACTIVE_CLIENT = key;
  await writeEnv(env);
}

/** A complete, ready-to-render ClientConfig template for a fresh store. */
export function blankStoreSource(name, slug, varName) {
  const img = (s) => `https://picsum.photos/seed/${slug}-${s}/800/1000`;
  const cat = (s) => `https://picsum.photos/seed/${slug}-${s}/900/1100`;
  const av = (s) => `https://picsum.photos/seed/${slug}-${s}/160/160`;
  const j = (v) => JSON.stringify(v);
  return `import type { ClientConfig } from "@/config/types";

/**
 * ${name} — created with \`npm run create-store\`. A complete, ready-to-use store.
 * Edit any of this content visually in /admin, or by hand below.
 */
export const ${varName}: ClientConfig = {
  brand: {
    name: ${j(name)},
    tagline: "Considered products, made well",
    description: ${j(`${name} — a curated selection of premium products, delivered worldwide.`)},
    email: ${j(`hello@${slug}.com`)},
    announcement: "Free shipping on orders over $75",
  },
  theme: { tokens: "app/globals.css" },
  header: {
    brandName: ${j(name)},
    announcement: "Free shipping on orders over $75",
    navLinks: [
      { label: "New In", href: "#featured" },
      { label: "Shop", href: "#categories" },
      { label: "Sale", href: "#flash-sale" },
      { label: "Bestsellers", href: "#bestsellers" },
      { label: "About", href: "#newsletter" },
    ],
  },
  footer: {
    brandName: ${j(name)},
    blurb: ${j(`${name} — a curated selection of premium products, made well and built to last.`)},
    columns: [
      { title: "Shop", links: [
        { label: "New Arrivals", href: "#featured" },
        { label: "Categories", href: "#categories" },
        { label: "Sale", href: "#flash-sale" },
      ] },
      { title: "Support", links: [
        { label: "Shipping & Returns", href: "#" },
        { label: "Contact Us", href: "#" },
        { label: "FAQ", href: "#" },
      ] },
      { title: "Company", links: [
        { label: "Our Story", href: "#" },
        { label: "Careers", href: "#" },
        { label: "Press", href: "#" },
      ] },
    ],
    socials: [
      { label: "Instagram", href: "#", icon: "instagram" },
      { label: "Twitter", href: "#", icon: "twitter" },
      { label: "Facebook", href: "#", icon: "facebook" },
      { label: "YouTube", href: "#", icon: "youtube" },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "#" },
      { label: "Terms of Service", href: "#" },
    ],
    locale: "United States (USD $)",
  },
  pages: {
    home: {
      sections: [
        { key: "hero", enabled: true },
        { key: "categories", enabled: true },
        { key: "featured", enabled: true },
        { key: "flashSale", enabled: true },
        { key: "bestSellers", enabled: true },
        { key: "trust", enabled: true },
        { key: "testimonials", enabled: true },
        { key: "newsletter", enabled: true },
      ],
    },
  },
  content: {
    hero: {
      eyebrow: "New Collection",
      title: { line1: "Welcome to", line2: ${j(name)} },
      description: "Replace this with your story. Premium products, thoughtfully made — start customizing in the admin.",
      primaryCta: { label: "Shop Now", href: "#featured" },
      secondaryCta: { label: "Browse Categories", href: "#categories" },
      ratingValue: "4.9",
      ratingSuffix: "1,000+ reviews",
      trustNote: "Free shipping · Easy returns",
      featuredBadge: "Bestseller",
      product: { id: "p-1", slug: "product-1", name: "Signature Product", category: "Featured", price: 120, rating: 4.9, reviewCount: 124, image: "${img("p1")}", badges: ["Bestseller"] },
    },
    categories: {
      heading: { eyebrow: "Shop by Category", title: "Find your edit", description: "A few collections to get you started — rename them in the admin.", action: { label: "All categories", href: "#" } },
      items: [
        { id: "c-1", name: "Collection One", slug: "one", image: "${cat("c1")}", itemCount: 24, featured: true },
        { id: "c-2", name: "Collection Two", slug: "two", image: "${cat("c2")}", itemCount: 18 },
        { id: "c-3", name: "Collection Three", slug: "three", image: "${cat("c3")}", itemCount: 31 },
        { id: "c-4", name: "Collection Four", slug: "four", image: "${cat("c4")}", itemCount: 12, featured: true },
      ],
    },
    featured: {
      heading: { eyebrow: "New In", title: "Featured products", description: "Your latest and best — swap these in the admin.", action: { label: "View all", href: "#" } },
      products: [
        { id: "f-1", slug: "f1", name: "Product One", category: "Featured", price: 120, rating: 4.8, reviewCount: 90, image: "${img("f1")}", badges: ["New"] },
        { id: "f-2", slug: "f2", name: "Product Two", category: "Featured", price: 95, rating: 4.7, reviewCount: 61, image: "${img("f2")}" },
        { id: "f-3", slug: "f3", name: "Product Three", category: "Featured", price: 160, rating: 4.9, reviewCount: 142, image: "${img("f3")}", badges: ["Bestseller"] },
        { id: "f-4", slug: "f4", name: "Product Four", category: "Featured", price: 80, rating: 4.6, reviewCount: 47, image: "${img("f4")}" },
      ],
    },
    flashSale: {
      badge: "Flash Sale", title: "Up to 25% off, this week", subtitle: "An example sale — disable this section anytime in the admin.",
      durationMs: ${(8 * 3600 + 30 * 60) * 1000},
      products: [
        { id: "s-1", slug: "s1", name: "Sale Product One", category: "Sale", price: 75, compareAtPrice: 100, rating: 4.7, reviewCount: 80, image: "${img("s1")}", badges: ["Limited"] },
        { id: "s-2", slug: "s2", name: "Sale Product Two", category: "Sale", price: 60, compareAtPrice: 80, rating: 4.6, reviewCount: 53, image: "${img("s2")}" },
      ],
    },
    bestSellers: {
      heading: { eyebrow: "Most Loved", title: "Bestsellers", description: "The products customers come back for.", action: { label: "Shop bestsellers", href: "#" } },
      products: [
        { id: "b-1", slug: "b1", name: "Bestseller One", category: "Popular", price: 130, rating: 4.9, reviewCount: 210, image: "${img("b1")}", badges: ["Bestseller"] },
        { id: "b-2", slug: "b2", name: "Bestseller Two", category: "Popular", price: 90, rating: 4.8, reviewCount: 150, image: "${img("b2")}" },
        { id: "b-3", slug: "b3", name: "Bestseller Three", category: "Popular", price: 110, rating: 4.7, reviewCount: 98, image: "${img("b3")}" },
        { id: "b-4", slug: "b4", name: "Bestseller Four", category: "Popular", price: 145, rating: 4.9, reviewCount: 175, image: "${img("b4")}" },
        { id: "b-5", slug: "b5", name: "Bestseller Five", category: "Popular", price: 70, rating: 4.6, reviewCount: 64, image: "${img("b5")}" },
        { id: "b-6", slug: "b6", name: "Bestseller Six", category: "Popular", price: 185, rating: 5.0, reviewCount: 41, image: "${img("b6")}", badges: ["Exclusive"] },
      ],
    },
    trust: {
      badges: [
        { icon: "truck", title: "Free Shipping", subtitle: "On orders over $75" },
        { icon: "refresh", title: "Easy Returns", subtitle: "30-day, no questions asked" },
        { icon: "shield", title: "Secure Checkout", subtitle: "Encrypted payments" },
        { icon: "headset", title: "Friendly Support", subtitle: "Here to help, 7 days a week" },
      ],
      brandLogos: ["AS SEEN IN", "VOGUE", "FORBES", "WIRED", "ELLE", "GQ"],
    },
    testimonials: {
      heading: { eyebrow: "Customer Stories", title: "Loved by customers", align: "center" },
      items: [
        { id: "t-1", quote: "Genuinely impressed — the quality exceeded my expectations and delivery was fast. I'll be back.", author: "Alex Morgan", role: "Verified Buyer", location: "New York, US", rating: 5, avatar: "${av("t1")}" },
        { id: "t-2", quote: "Beautiful products, thoughtful packaging, and effortless returns. Exactly how shopping should feel.", author: "Sam Rivera", role: "Verified Buyer", location: "London, UK", rating: 5, avatar: "${av("t2")}" },
        { id: "t-3", quote: "Customer support was quick and kind. The product is even better in person. Highly recommend.", author: "Jordan Lee", role: "Verified Buyer", location: "Toronto, CA", rating: 5, avatar: "${av("t3")}" },
      ],
    },
    newsletter: {
      title: "Join our list", description: "Get early access to new arrivals and members-only offers. Enjoy 10% off your first order.",
      placeholder: "Enter your email", submitLabel: "Subscribe",
      successMessage: "You're in — your 10% code is on its way.", disclaimer: "No spam. Unsubscribe anytime.",
    },
  },
};
`;
}

/* ── core ─────────────────────────────────────────────────────────────────── */

export async function createStore(name, { activate = true } = {}) {
  if (!name || !name.trim()) throw new Error('Please provide a store name, e.g. npm run create-store "Acme Store"');

  let slug = slugify(name);
  if (!slug) throw new Error(`Could not derive a store id from "${name}".`);
  // Created stores are PRODUCTION by convention — never the reserved demo prefix.
  if (slug.startsWith("demo-")) slug = `store-${slug}`;

  let registry = await fs.readFile(REGISTRY, "utf8");
  if (registry.includes(`"${slug}":`)) {
    throw new Error(`A store with id "${slug}" already exists. Choose a different name.`);
  }

  const varName = toVarName(slug);

  // 1) write the store config
  await fs.mkdir(CLIENTS_DIR, { recursive: true });
  const file = path.join(CLIENTS_DIR, `${slug}.ts`);
  await fs.writeFile(file, blankStoreSource(name.trim(), slug, varName), "utf8");

  // 2) register it (import + registry entry, via the codegen markers)
  registry = insertBeforeMarker(registry, "// @factory:imports", `import { ${varName} } from "@/clients/${slug}";`);
  registry = insertBeforeMarker(registry, "// @factory:stores", `"${slug}": ${varName},`);
  await fs.writeFile(REGISTRY, registry, "utf8");

  // 3) make it the active store (production mode)
  if (activate) await setActiveStore(slug, "production");

  return { slug, varName, file };
}

/* ── CLI entry ────────────────────────────────────────────────────────────── */

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  const name = process.argv.slice(2).filter((a) => a !== "--").join(" ").trim();
  try {
    const { slug, file } = await createStore(name);
    console.log(`\n✓ Store created: "${name}"  (id: ${slug})`);
    console.log(`  • config:   clients/${slug}.ts`);
    console.log(`  • registered + set as the active store`);
    console.log(`\nNext:`);
    console.log(`  1. npm run dev        → open http://localhost:3000`);
    console.log(`  2. open /admin        → customise brand, sections and products`);
    console.log(`  3. map your domain in config/tenant-resolver.ts before deploying\n`);
  } catch (err) {
    console.error(`\n✗ ${err.message}\n`);
    process.exit(1);
  }
}
